<?php
/**
 * Implements hook_form_alter().
 *
 * Hide average fivestar field from review edit/create form.
 */
function eshop_rating_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'service_order_node_form') {
    // Hide average field, this field is calculated upon node_presave.
    $form['field_overall_rate']['#access'] = FALSE;
  }
}

/**
 * Implements hook_node_presave().
 *
 * Calculates average vote rating.
 */
function eshop_rating_node_update($node) {
  if ($node->type == 'service_order') {
    // Get values from 3 axis.
    $first_rate      = entity_metadata_wrapper('node', $node)->field_first_rate->value();
    $second_rate      = entity_metadata_wrapper('node', $node)->field_second_rate->value();
    $third_rate    = entity_metadata_wrapper('node', $node)->field_third_rate->value();

    // Calculate and set average axe.
    $overall      = ($first_rate + $second_rate + $third_rate) / 3;
    // @info: Can't use entity_metadata_wrapper, because '->set' not supported on this field.
    //entity_metadata_wrapper('node', $node)->field_review_votes_average->set($votes_average);
    $node->field_overall_rate['und'][0]['rating'] = $overall;  
  }
}
?>